# Generated by Django 4.1 on 2022-08-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("hdd", models.TextField()),
                ("hdd_unavailable", models.TextField()),
                ("product_id", models.CharField(max_length=20)),
                ("price", models.CharField(max_length=20)),
                ("reviews", models.CharField(max_length=50)),
                ("starts", models.PositiveIntegerField()),
                ("product_infos", models.CharField(max_length=256)),
            ],
        ),
    ]
